export const LoginInputs = {
  email: {
    htmlFor: "inputEmail",
    labelClassName: "sr-only custom--label",
    labelText: "Email address",
    type: "Email",
    id: "inputEmail",
    className: "form-control",
    placeholder: "Enter Email address",
    name: "email",
    required: true,
    autoFocus: true,
  },
  password: {
    htmlFor: "inputPassword",
    labelClassName: "sr-only custom--label",
    labelText: "Password",
    type: "password",
    id: "inputPassword",
    className: "form-control",
    placeholder: "Enter Password",
    name: "password",
    required: true,
    autoFocus: false,
  },
};

export const SignUpInputs = {
  user: {
    htmlFor: "inputUser",
    labelClassName: "sr-only custom--label",
    labelText: "User Name",
    type: "text",
    id: "inputUser",
    className: "form-control",
    placeholder: "Enter User Name",
    name: "user",
    required: true,
    autoFocus: true,
  },
  email: {
    htmlFor: "inputEmail",
    labelClassName: "sr-only custom--label",
    labelText: "Email address",
    type: "Email",
    id: "inputEmail",
    className: "form-control",
    placeholder: "Enter Email address",
    name: "email",
    required: true,
    autoFocus: true,
  },
  password: {
    htmlFor: "inputPassword",
    labelClassName: "sr-only custom--label",
    labelText: "Password",
    type: "password",
    id: "inputPassword",
    className: "form-control",
    placeholder: "Enter Password",
    name: "password",
    required: true,
    autoFocus: false,
  },
};
